apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

managedNodeGroups:
  - name: expense 
    instanceTypes: ["t3.mirco","t3.mirco","t4.mirco","t5.mirco"]
    desiredCapacity: 3
    spot: true